# Generated by Django 4.1.7 on 2023-02-22 13:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('tipo_imovel', models.CharField(choices=[('APARTAMENTO', 'APARTAMENTO'), ('KITNET', 'KITNET'), ('CASA', 'CASA'), ('LOFT', 'LOFT')], max_length=100)),
                ('descricao', models.TextField()),
                ('endereco', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_locate', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Locatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('cpf', models.CharField(max_length=14)),
            ],
            options={
                'verbose_name': 'Locatário',
                'verbose_name_plural': 'Locatários',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RegistrarLocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_inicio', models.DateTimeField(verbose_name='Inicio Contrato')),
                ('dt_fim', models.DateTimeField(verbose_name='Fim Contrato')),
                ('criado', models.DateField(blank=True, default=datetime.datetime.now)),
                ('Imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_locacao', to='myapp.imovel')),
                ('Locatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.locatario')),
            ],
            options={
                'verbose_name': 'Registrar Locação',
                'verbose_name_plural': 'Registrar Locações',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ImagemImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', verbose_name='Images')),
                ('Imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imovel_imagens', to='myapp.imovel')),
            ],
            options={
                'verbose_name': 'Imagem do Imóvel',
                'verbose_name_plural': 'Imagens do Imóvel',
                'ordering': ['-id'],
            },
        ),
    ]
